### PR TITLE
Awaiting review

### PR DESCRIPTION
**Pull request by KirraKotsenburg**
Had to fix the repo, every test passing now

### CODE REVIEW

**Comment by Cromie1** [comment]
add to your gitignore
firmware.elf
main.i
main.o
main.s
second.o

**Comment by Cromie1** [comment]
I think these files may possibly be causing you to fail the test.

**Comment by Cromie1** [comment]
I am  struggling to see how It isn't passing the hello test the second time

**Comment by KirraKotsenburg** [comment]
> I am struggling to see how It isn't passing the hello test the second time
Okay I actually was just looking into this, and apparently the CMake/build(pull_request) is run on the main branch which would make sense since I'm seeing files that Skylar committed which don't exist on the branch under review:
image

**Review by Cromie1 — APPROVED** [review]
Considering you pass all tests and I have checked the YML as well as the makelist. I see no issues other than the tests failing the second time. This is due to your main branch being incorrect but the changes made should fix that.

**Review by VarunBhavya — APPROVED** [review]
Upon review, the file seems to be in order. Following Alex’s instructions should ensure everything is correct.

**Review by EddieFranco — APPROVED** [review]
I have checked our code and yours and they look correct, wondering why the test between branches make that error in testing,  otherwise It looks good to me.

**Pull request merged**
